const conf = {
  BaseURL: String(import.meta.env.VITE_BASE_URL),
  SignupUrl: "/auth/signup",
  LoginUrl: "/auth/login",
  GetAllCategoryUrl: "/category/getAllCategory",
  GetImageUrl: "/upload",
  GetAllProductUrl: "/product/getAllProducts",
  GetAllBanner: "/banner/getAllBanner",
  GetAllPoster: "/poster/getAllPoster",
  GetNewArrivalProduct: "/product/newArrivalsProduct",
  GetFeaturedProduct: "/product/featuredProducts",
  GetTrendingProduct: "/product/getTrendingProducts",
  PostRecentlyViwedProduct: "/product/postrecentlyViwedProduct",
  GetRecentlyViwedProducts: "/product/getRecentlyViewdProduct",
  GetSingleProductUrl: "/product/getSingleProduct",
  GetSimilorProduct: "/product/getSimilorProduct",
  GetRecommendedProduct: "/product/getRecommendedProduct",
  GetCartProductUrl: "/cart/getCartProduct",
  AddProductInCartUrl: "/cart/addProductInCart",
  DeleteProductFromCartUrl: "/cart/deleteProductFromCart",
  updateProductQuantityInCartUrl: "/cart/updateCartProductQuantity",
  GetWishlistProductUrl: "/wishlist/getWishlistProduct",
  AddProductInWishlistUrl: "/wishlist/addProductInwishlist",
  DeleteProductFromWishlistUrl: "/wishlist/removeProductFromWishlist",
  GetAllSubcategoryUrl: "/subcategory/getAllSubcategory",
  GetFilteredProductsUrl: "/product/getFilteredProducts",
  GetBrandUrl: "/brand/getAllBrand",
  GetPriceRangeUrl: "/priceRange/getPriceRanges",
  CreatePriceRangeUrl: "/priceRange/createPriceRange",
  GetSingleSubcategoryUrl: "/subcategory/getSingleSubcategory",
  getMultipleSubcategoriesUrl: "/subcategory/getMultipleSubcategories",
  getDiscountOptionsUrl: "/discountOptions/getDiscountOptions",
  createDiscountOptionsModel: "/discountOptions/createDiscountOptions",
  getFilteredProductsUrl: "/product/getFilteredProducts",
  postDeliveryInfoUrl: "/deliveryInfo/postdeliveryInfoUser",
  getDeliveryInfoUrl: "/deliveryInfo/getDeliveryInfoUser",
  CreateProductUrl: "/product/createProduct",
  deleteProductUrl: "/product/deleteProduct",
  editProductUrl: "/product/updateProduct",
  deleteMultipleProductUrl: "/product/deleteMultipleProduct",
  getFilteredCategoriesUrl: "/category/getFilteredCategories",
  createCategoryUrl: "/category/createCategory",
  deleteCategoryUrl: "/category/deleteCategory",
  deleteMultipleCategoryUrl: "/category/deleteMultipleCategory",
  getSingleCategoryUrl: "/category/getSingleCategory",
  editCategoryUrl: "/category/updatedCategory",
  deleteSubcategoryUrl: "/subcategory/deleteSubcategory",
  deleteMultipleSubcategoriesUrl: "/subcategory/deleteMultipleSubcategory",
  getFilteredSubategoriesurl: "/subcategory/getFilteredSubategories",
  createSubcategoryUrl: "/subcategory/createSubcategory",
  getSingleSubcategoryUrl: "/subcategory/getSingleSubcategory",
  editSubcategoryUrl: "/subcategory/updatedSubcategory",
  deleteBrandUrl: "/brand/deleteBrand",
  getFilteredBrandUrl: "/brand/getFilteredBrand",
  createBrandUrl: "/brand/createBrand",
  singleBrandUrl: "/brand/getSingleBrand",
  editBrandUrl: "/brand/updatedBrand",
  deleteMultipleBrandUrl: "/brand/deleteMultipleBrand",
  getAllSubcategoryByCategoryUrl: "/subcategory/getAllSubcategoryByCategory",
  getAllBrandBySubcategoryUrl: "/brand/getAllBrandBySubcategory",
  getAllBrandByCategoryUrl: "/brand/getAllBrandByCategory",
  getAllBrandByMultipleSubcategoryUrl:
    "/brand/getAllBrandByMultipleSubcategory",
  placeOrderUrl: "/order/placeOrder",
  getUsersUrl:"/users/getUsers",
  getFilteredUsersUrl:"/users/getFilteredUsers",
  createUserUrl: "/users/createUser",
  getSingleUserUrl: "/users/getSingleUser",
  updateUserUrl: "/users/updateUser",
  getUserOrdersUrl: "/order/getUserOrders",
  createBannerUrl: "/banner/createBanner",
  deleteBannerUrl: "/banner/deleteBanner",
  updateBannerUrl: "/banner/updateBanner",
  getSingleBannerUrl: "/banner/getSingleBanner",
  getAllOrders: "/order/getAllOrders",
  deleteOrderUrl: "/order/deleteOrder",
  getFilteredOrdersUrl: "/order/getFilteredOrders",
  updateOrderStatusUrl: "/order/updateOrderStatus",
  deletePosterUrl: "/poster/deletePoster",
  createPosterUrl: "/poster/createPoster",
  GetImageUrl: "/upload/",
  ClearCartUrl: "/cart/clearCart",
  getRolesUrl: "/role/getRoles",
  getSingleRoleUrl: "/role/getSingleRole",
  createRoleUrl: "/role/createRole",
  deleteRoleUrl: "/role/deleteRole",
  deleteMultipleRoleUrl: "/role/deleteMultipleRole",
  updateRoleUrl: "/role/updateRole",
  getFilteredRolesUrl: "/role/getFilteredRoles",
  getPermissionsUrl: "/permission/getPermissions",
  createPermissionUrl: "/permission/createPermission",
  deletePermissionUrl:"/permission/deletePermission",
  deleteMultiplePermissionUrl:"/permission/deleteMultiplePermission",
  getFilteredPermissionUrl:"/permission/getFilteredPermission",
  getSinglePermissionUrl:"/permission/getSinglePermission",
  updatePermissionUrl:"/permission/updatePermission",
  saveForLetterProductUrl:"/saveforletters/saveForLater",
  getSaveForLaterProductUrl: "/saveforletters/getSavedForLater",
  removeSaveForLaterProductUrl:"/saveforletters/saveForLaterProductRemove"
};

export default conf;
