const conf = {
  BaseURL: String(import.meta.env.VITE_BASE_URL),
  SignupUrl: "/auth/signup",
  LoginUrl: "/auth/login",
  GetAllCategoryUrl: "/category/getAllCategory",
  GetImageUrl: "/upload",
  GetAllProductUrl: "/product/getAllProducts",
  GetAllBanner: "/bannerRoutes/getAllBanner",
  GetAllPoster: "/posterRoutes/getAllPoster",
  GetNewArrivalProduct: "/product/newArrivalsProduct",
  GetFeaturedProduct: "/product/featuredProducts",
  GetTrendingProduct: "/product/getTrendingProducts",
  PostRecentlyViwedProduct: "/product/postrecentlyViwedProduct",
  GetRecentlyViwedProducts: "/product/getRecentlyViewdProduct",
  GetSingleProductUrl: "/product/getSingleProduct",
  GetSimilorProduct: "/product/getSimilorProduct",
  GetRecommendedProduct: "/product/getRecommendedProduct",
  GetCartProductUrl: "/cart/getCartProduct",
  AddProductInCartUrl: "/cart/addProductInCart",
  DeleteProductFromCartUrl: "/cart/deleteProductFromCart",
  updateProductQuantityInCartUrl: "/cart/updateCartProductQuantity",
  GetWishlistProductUrl: "/wishlist/getWishlistProduct",
  AddProductInWishlistUrl: "/wishlist/addProductInwishlist",
  DeleteProductFromWishlistUrl: "/wishlist/removeProductFromWishlist",
  GetAllSubcategoryUrl: "/subcategory/getAllSubcategory",
  GetFilteredProductsUrl: "/product/getFilteredProducts",
  GetBrandUrl: "/brand/getAllBrand",
  GetPriceRangeUrl: "/priceRange/getPriceRanges",
  CreatePriceRangeUrl:"/priceRange/createPriceRange",
  GetSingleSubcategoryUrl:"/subcategory/getSingleSubcategory",
  getMultipleSubcategoriesUrl:"/subcategory/getMultipleSubcategories",
  getDiscountOptionsUrl:"/discountOptions/getDiscountOptions",
  createDiscountOptionsModel:"/discountOptions/createDiscountOptions",
  getFilteredProductsUrl:"/product/getFilteredProducts",
  postDeliveryInfoUrl:"/deliveryInfo/postdeliveryInfoUser",
  getDeliveryInfoUrl:"/deliveryInfo/getDeliveryInfoUser",
  CreateProductUrl:"/product/createProduct",
  deleteProductUrl:"/product/deleteProduct",
  editProductUrl:"/product/updateProduct",
  deleteMultipleProductUrl:"/product/deleteMultipleProduct",
  getFilteredCategoriesUrl:"/category/getFilteredCategories",
  createCategoryUrl:"/category/createCategory",
  deleteCategoryUrl:"/category/deleteCategory",
  deleteMultipleCategoryUrl:"/category/deleteMultipleCategory",
  getSingleCategoryUrl:"/category/getSingleCategory",
  editCategoryUrl:"/category/updatedCategory",
  deleteSubcategoryUrl:"/subcategory/deleteSubcategory",
  deleteMultipleSubcategoriesUrl:"/subcategory/deleteMultipleSubcategory",
  getFilteredSubategoriesurl:"/subcategory/getFilteredSubategories",
  createSubcategoryUrl:"/subcategory/createSubcategory",
  getSingleSubcategoryUrl:"/subcategory/getSingleSubcategory",
  editSubcategoryUrl:"/subcategory/updatedSubcategory",
  deleteBrandUrl:"/brand/deleteBrand",
  getFilteredBrandUrl:"/brand/getFilteredBrand",
  createBrandUrl:"/brand/createBrand",
  singleBrandUrl:"/brand/getSingleBrand",
  editBrandUrl:"/brand/updatedBrand",
  deleteMultipleBrandUrl:"/brand/deleteMultipleBrand"
};

export default conf;
